### PR TITLE
Update BlockDeviceZfs.filesystem_{info,type} to handle dataset device paths

### PR DESCRIPTION
**Pull request by tanabarr**
filesystem_type returns None if zpool has no datasets, 'zfs' otherwise and does this by calling filesystem_info which returns a list of the datasets or None if no datasets.

change both methods to accept  dataset paths, needed for https://github.com/intel-hpdd/intel-manager-for-lustre/pull/174

### CODE REVIEW

**Comment by tanabarr** [comment]
as this introduces  API changes and will break tests, minor version should be bumped (observing semver) to 1.1.0

**Comment by jgrund** [comment]
Can this be closed?

**Comment by tanabarr** [comment]
I don't think we should close this yet, it's not yet irrelevant (maybe soon but I'm not sure yet

**Comment by jgrund** [comment]
What's still needed in this area?

**Pull request closed without merging**
